import type { Metadata } from "next";
import "./globals.css";
import React, { Suspense } from "react";
import { LanguageProvider } from "@/contexts/LanguageContext";
import MatrixBackground from "@/components/matrix-background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Suspense fallback={<div>Loading...</div>}>
          <MatrixBackground />
        </Suspense>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
